# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               tip4programs
tagline:             'tips for python programs'
description:         '<a href="https://python.org" target="_blank">Python</a>.'
url:                 http://lanyon.getpoole.com
baseurl:             '/lanyon'
paginate:            5

# About/contact
author:
  name:              Anuja K Soman
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
